#确定当前版本为发布版本，即active：prod，配置数据库、用户名密码、
spring:
  profiles:
    active: prod
#    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.245.150.40:3306/vote_system
#    url: jdbc:mysql://localhost:3306/vote_system
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
